CREATE TABLE IF NOT EXISTS teams (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  lead_id INTEGER NULL
);

CREATE TABLE IF NOT EXISTS people (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(120) NOT NULL,
  role VARCHAR(60) NOT NULL,
  velocity NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (velocity >= 0 AND velocity <= 100),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  team_lead_id INTEGER NULL REFERENCES people(id) ON DELETE SET NULL
);
